# The Site Configuration
encoding: utf-8

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai

# -----------------------------------------------------------------------------
# SEO
# -----------------------------------------------------------------------------
serve_og_meta: true
serve_schema_org: true

# Fill in the protocol & hostname for your site.
# e.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://jinchaoli.com"

# The base URL of your site
baseurl: ""

icon: 🎓

title: Jinchao Li # the main title

tagline: Jinchao Li's Homepage # it will display as the subtitle

description: >- # used by seo meta and the atom feed
  Jinchao Li's Homepage

keywords: jinchao li, 李锦超, cuhk, 香港中文大学, research, speech and natural language processing

github:
  username: JinchaoLove # change to your github username

twitter:
  username: JinchaoLove # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Jinchao Li
  email: jinchaolovefy@gmail.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/JinchaoLove # change to your github homepage
    - https://scholar.google.com/citations?hl=en&user=0LWE_dkAAAAJ # googlescholar
    - https://www.researchgate.net/profile/Jinchao-Li-3 # researchgate
    - https://twitter.com/JinchaoLove # twitter
    - https://zhihu.com/people/jinchaoli # zhihu
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# fill in to your verification string, https://search.google.com/search-console
google_site_verification: HThdAzjrnhHpjRsmk25neOUBYDdhUX4oDJeeiHMwcSQ

google_analytics:
  id: # fill in your Google Analytics ID

# -----------------------------------------------------------------------------
# Basic Settings
# -----------------------------------------------------------------------------

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: # [light | dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: "/assets/img/avatar/Jinchao.png" #"/commons/avatar.jpg"

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
# It can be overridden by a customized `page.image` in front matter.
social_preview_image: # string, local or CORS resources

# boolean type, the global switch for TOC, lazy_polyfill, etc.
nav_blog: true
toc: true
lazy_polyfill: true
magnific_popup: true
clipboard: true
dayjs: true

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: true # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: production # [development | production]

pwa:
  enabled: true # the option for PWA feature
  cache:
    enabled: true # the option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

paginate: 10
paginate_path: "/blog/page:num/"

# -----------------------------------------------------------------------------
# Built-in search
# -----------------------------------------------------------------------------
# https://github.com/just-the-docs/just-the-docs/blob/main/docs/search.md

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 6
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 6
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Trigger search by pressing `ctrl` (or `cmd` on macOS) + `shortcut_key`
  # Exit search by pressing `Escape`
  shortcut_key: "k"

# Use front-matter `search_exclude: true` to exclude a page from search.
# To customize search indexing, use `search/lunr/*`:
#   - `custom-item.json` to add an item
#   - `custom-data.json` to add key-value pairs for each page
#   - `custom-index.js` to modify each item before searching

# -----------------------------------------------------------------------------
# Comments
# -----------------------------------------------------------------------------

comments:
  provider: waline # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The provider options are as follows:
  waline:
    server_url: https://comment.jinchaoli.com
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------
# https://github.com/inukshuk/jekyll-scholar

scholar:
  last_name: [Li]
  first_name: [Jinchao]

  style: apa
  locale: en

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib # _layouts/bib.html
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  # See https://github.com/alshedivat/al-folio/issues/357.
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true
  remove_duplicates: true

  query: "@*"
  group_by: year
  group_order: descending

# Display different badges withs stats for your publications
enable_publication_badges:
  altmetric: false # Altmetric badge (https://www.altmetric.com/products/altmetric-badges/)
  dimensions: false # Dimensions badge (https://badge.dimensions.ai/)

# Filter out certain bibtex entry keywords used internally from the bib output
filtered_bibtex_keywords:
  [
    abbr,
    abstract,
    arxiv,
    bibtex_show,
    pdf,
    selected,
    supp,
    blog,
    code,
    demo,
    poster,
    slides,
    video,
    website,
    preview,
    altmetric,
    max_author_limit,
  ]

# Maximum number of authors to be shown for each publication (more authors are visible on click)
max_author_limit: 7 # leave blank to always show all authors
more_authors_animation_delay: 10 # more authors are revealed on click using animation; smaller delay means faster animation

# Enables publication thumbnails. If disabled, none of the publications will display thumbnails, even if specified in the bib entry.
enable_publication_thumbnails: true

# -----------------------------------------------------------------------------
# KramDown
# -----------------------------------------------------------------------------

kramdown:
  input: GFM  # 启用 GitHub Flavored Markdown，支持 emoji 别名（如 :smile:）。
  hard_wrap: true
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------
# MAKE SURE imagemagick is installed and on your PATH before enabling imagemagick. In a terminal, run: `convert -version`
# Recommended to enable, see https://github.com/alshedivat/al-folio/issues/537)

imagemagick:
  enabled: true
  widths:
    - 480 # 270p
    - 800 # 450p
    - 1280 # 720p
  input_directories:
    - assets/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
  output_formats:
    webp: "-quality 75"

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /blog/tags/:name/
    category: /blog/categories/:name/

# -----------------------------------------------------------------------------
# Jekyll Feed
# -----------------------------------------------------------------------------

feed:
  posts_limit: 5
  tags: true

# -----------------------------------------------------------------------------
# Others
# -----------------------------------------------------------------------------

# Sitemap settings
defaults:
  # blog home
  - scope:
      path: "blog"
    values:
      articles:
        excerpt_type: html
  # posts
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /blog/:title/ # /posts/:title/
  # drafts
  - scope:
      path: _drafts
    values:
      comments: false
  # tabs
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  # cache
  - scope:
      path: assets/img
    values:
      swcache: true
  - scope:
      path: assets/papers
    values:
      swcache: true

# Pages
destination: _site/

collections:
  tabs:
    output: true
    sort_by: order

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

keep_files:
  - CNAME
  - .nojekyll

jekyll-minifier:
  # exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  preserve_php: true               # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true     # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: false         # Default: true
  compress_json: false               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: true       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  terser_args:                      # Default: (empty)
  # uglifier_args:
  #   harmony: true                   # Enable to support ES6+

# Plugins
plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-include-cache
  - jekyll-jupyter-notebook
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-scholar
  - jekyll-sitemap
