#!/usr/bin/env bash

printf '+-%.0s' {1..100}

ruby -e 'puts Encoding.default_external'
ruby -e 'puts Encoding.default_internal'

# locale
# locale -a
export LANG="en_US.utf8"
export LANGUAGE="en_US.utf8"
export LC_ALL="en_US.utf8"
export RUBYOPT="-E utf-8:utf-8"

bash tools/clean

printf '+-%.0s' {1..80}

pip3 -V
# pip 25.1.1 from /opt/buildhome/.asdf/installs/python/3.13.3/lib/python3.13/site-packages/pip (python 3.13)

pip_output=$(pip -V 2>&1)
path_in_pip=$(echo "$pip_output" | sed -n 's/.* from \(.*lib.*\)/\1/p')
echo "pip path: $path_in_pip"
ls $(dirname "$path_in_pip") | grep jupyter
PYTHON_PREFIX=$(dirname "$(dirname "$path_in_pip")")
export PATH="$PATH:$PYTHON_PREFIX/bin"
echo $PATH

pip3 install -q jupyter
# pip3 install -q --upgrade --force-reinstall jupyter
python3 tools/generate_markmap.py convert_all

echo "jupyter"
which jupyter
jupyter --version
python3 -c "import notebook; print(notebook.__version__)"
python3 -m pip show jupyter

printf '+-%.0s' {1..100}
npm i && npm run build
bundle
JEKYLL_ENV=production bundle exec jekyll b -d "_site"
