#!/usr/bin/env bash
USER_NAME="JinchaoLove"
CURRENT_DIR="$(pwd)"
GH_DIR="$(pwd)/../$USER_NAME.github.io"
# prepare github pages
if [ ! -d $GH_DIR ]; then
    cd ..
    git clone git@github.com:$USER_NAME/$USER_NAME.github.io.git
fi
cd $GH_DIR
git pull
# build
cd $CURRENT_DIR
rm -rf _site
bash/build
# push
cd _site
cp -r $GH_DIR/.git .
git add .
git commit -m "gh-pages"
git push -f origin main
# remove
cd $CURRENT_DIR
# rm -rf _site
