#!/usr/bin/env bash
#
# Run jekyll serve and then launch the site

bash tools/clean
pip3 install -q jupyter
python3 tools/generate_markmap.py convert_all

npm i && npm run build
bundle
JEKYLL_ENV="production" bundle exec jekyll s
